site_name: My Blog
# site_url: https://athameral.github.io

theme:
  name: material
  # locale: zh_CN

markdown_extensions:
  - toc:
      permalink: "#"
  
  # mathjax
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 主页: index.md
  - 专业课:
    - 大数据与数据工程: subjects/BDDE/index.md
    - 自动控制原理: subjects/ACT/index.md
  - 技巧:
    - SSH: techniques/SSH/index.md
    - Android: techniques/Android/index.md